on:
  push:
    branches:
      - "*/[0-9]+-*"
      - "!dev"

name: create pull request

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: get username
        id: username
        run: |
          username=$(echo ${{github.ref_name}} | cut -d/ -f1)
          echo "$username"
          echo "USERNAME=$username" $GITHUB_OUTPUT

      - name: get branch name
        id: branch_name
        run: |
          branch_name=$(echo ${{github.ref_name}} | cut -d/ -f2 | cut -d- -f2- | tr '-' ' ')
          capitalized_branch_name=$(echo "${branch_name^}")
          echo "$branch_name"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_OUTPUT

      - name: get issue number
        id: issue_number
        run: |
          issue_num=$(echo ${{ github.ref_name }} | cut -d/ -f2 | cut -d- -f1)
          echo "$issue_num"
          echo "ISSUE_NUM=$issue_num" >> $GITHUB_OUTPUT

      - name: raise PR
        if: ${{(github.actor == steps.username.outputs.USERNAME)}}
        run: |
          gh pr create --assignee "${{ github.actor }}" --draft --base dev --head ${{ github.ref_name }} --title "${{ steps.branch_name.outputs.BRANCH_NAME }}" --body "[Issue Number ${{steps.issue_number.outputs.ISSUE_NUM}}](https://github.com/Yuvalg1/boardman/issues/${{steps.issue_number.outputs.ISSUE_NUM}})"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
