on:
  pull_request:
    types: [converted_to_draft]

name: add in progress label to issue

env:
  LABEL_TO_REMOVE: "waiting%20for%20CR"
  LABEL_TO_ADD: "in progress"

jobs:
  add-in-progress-label:
    runs-on: ubuntu-latest
    steps:
      - name: calculate issue number
        run: |
          PR_BODY=$(echo "${{ github.event.pull_request.body }}" | jq -r .body)
          ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oP '\[#\K\d+(?=\])')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: remove code review label
        run: |
          curl -g -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels/$LABEL_TO_REMOVE"

      - name: add in progress Label
        run: |
          if [ ! -z "$ISSUE_NUMBER" ]; then
            curl -g -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"labels":[ $LABEL_TO_ADD ]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels"
          fi
