on:
  pull_request:
    types: [converted_to_draft]

name: add in progress label to issue

env:
  LABEL_TO_REMOVE: "waiting%20for%20CR"
  LABEL_TO_ADD: "in progress"

jobs:
  calculate-issue-number:
    runs-on: ubuntu-latest
    outputs:
      ISSUE_NUMBER: ${{ steps.set_issue_number.outputs.var_value }}
    steps:
      - name: calculate issue number
        id: set_issue_number
        run: |
          pr_body=${{ github.event.pull_request.body }}
          issue_number=$(echo "$pr_body" | grep -o '#[0-9]\+' | sed 's/#//')
          echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV

  convert-to-draft-add-in-progress-label:
    runs-on: ubuntu-latest
    needs: calculate-issue-number
    steps:
      - name: remove code review label
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ needs.calculate-issue-number.outputs.ISSUE_NUMBER }}/labels/$LABEL_TO_REMOVE"

      - name: add in progress Label
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"labels":[ $LABEL_TO_ADD ]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ needs.calculate-issue-number.outputs.ISSUE_NUMBER }}/labels"
