on:
  pull_request:
    types: [opened, reopened]

name: add in progress label to issue

env:
  LABEL_TO_ADD: "in progress"

jobs:
  add-in-progress-label:
    runs-on: ubuntu-latest
    steps:
      - name: calculate issue number
        run: |
          pr_body=${{ github.event.pull_request.body }}
          issue_number=$(echo "$pr_body" | grep -o '#[0-9]\+' | sed 's/#//')
          echo "ISSUE_NUMBER=$issue_number" >> $GITHUB_ENV

      - name: add in progress label
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"labels":[ $LABEL_TO_ADD ]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels"
