on:
  pull_request:
    types: [opened, reopened]

name: add in progress label to issue

env:
  ISSUE_NUMBER: $(echo "${{ github.event.pull_request.body }}" | cut -d# -f2 | cut -d ' ' -f1 | grep -o '[0-9]*')

jobs:
  add-in-progress-label:
    runs-on: ubuntu-latest
    steps:
      - name: add in progress label
        run: |
          if [ ! -z "$ISSUE_NUMBER" ]; then
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"labels":["in progress"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels"
          fi
