on:
  pull_request:
    types: [opened, reopened]

name: add in progress label to issue

env:
  LABEL_TO_ADD: "in progress"

jobs:
  add-in-progress-label:
    runs-on: ubuntu-latest
    steps:
      - name: calculate issue number
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oP '\[#\K\d+(?=\])')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: add in progress label
        run: |
          if [ ! -z "$ISSUE_NUMBER" ]; then
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"labels":[ $LABEL_TO_ADD ]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels"
          fi
