on:
  pull_request:
    types: [ready_for_review]

name: add code review label to issue

jobs:
  add-code-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: remove in progress label
        run: |
          LABEL_TO_REMOVE="in progress"
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | cut -d# -f2 | cut -d ' ' -f1)

          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels/$LABEL_TO_REMOVE"

      - name: add code review Label
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | cut -d# -f2 | cut -d ' ' -f1)
          if [ ! -z "$ISSUE_NUMBER" ]; then
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"labels":["waiting for CR"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels"
          fi
